class Statics(object):

    Socio_Econ_Data_Years = {
                "2007-2011": "2011",
                "2012-2016": "2016"
               }

    Socio_Econ_Data_Columns = {
               "2011": {"id": "id",
                        "bgid2011": "geoid",
                        "estpopulation_2011": "EstTotalPopulation",
                        "estresidentialdensity_2011": "EstResidentialDensity",
                        "estmedianhouseholdincome_2011": "MedianHouseholdIncome",
                        "estpropnonhispwhite_2011": "EstPropNonHispWhite",
                        "estprophighschoolmaxeducation_2011": "EstPropHighSchoolMaxEducation",
                        "estpropnoauto_2011": "EstPropHouseholdsNoAuto",
                        "estpropesl_2011": "EstPropPersons5PlusNoEnglish",
                        "estpropfemalehouseholdnospouse_2011": "EstPropFemaleHouseholdNoSpouse",
                        "estpropfemalehouseholdfamilychild_2011": "EstPropFemaleHouseholdFamilyChild",
                        "estpropfemalehouseholdanychild_2011": "EstPropFemaleHouseholdAnyChild",
                        "estprophighschooldropout_2011": "EstPropHighSchoolDropout",
                        "estprophighschooldropoutnowork_2011": "EstPropHighSchoolDropoutNoWork",
                        "estprophouseholdssi_2011": "EstPropHouseholdSSI",
                        "estprophouseholdpa_2011": "EstPropHouseholdPA",
                        "estpropmalelittlework_2011": "EstPropMaleLittleWork"},
               "2016": {"id": "id",
                        "bgid2016": "geoid",
                        "estpopulation_2016": "EstTotalPopulation",
                        "estpopulation_2016se": "EstTotalPopulation_SE",
                        "estresidentialdensity_2016": "EstResidentialDensity",
                        "estresidentialdensity_2016se": "EstResidentialDensity_SE",
                        "estmedianhouseholdincome_2016": "MedianHouseholdIncome",
                        "estmedianhouseholdincome_2016se": "MedianHouseholdIncome_SE",
                        "estpropnonhispwhite_2016": "EstPropNonHispWhite",
                        "estpropnonhispwhite_2016se": "EstPropNonHispWhite_SE",
                        "estprophighschoolmaxeducation_2016": "EstPropHighSchoolMaxEducation",
                        "estprophighschoolmaxeducation_2016se": "EstPropHighSchoolMaxEducation_SE",
                        "estpropnoauto_2016": "EstPropHouseholdsNoAuto",
                        "estpropnoauto_2016se": "EstPropHouseholdsNoAuto_SE",
                        "estpropesl_2016": "EstPropPersons5PlusNoEnglish",
                        "estpropesl_2016se": "EstPropPersons5PlusNoEnglish_SE",
                        "estpropnohealthins_2016": "EstPropPersonsNoHealthIns",
                        "estpropnohealthins_2016se": "EstPropPersonsNoHealthIns_SE",
                        "estpropfemalehouseholdnospouse_2016": "EstPropFemaleHouseholdNoSpouse",
                        "estpropfemalehouseholdnospouse_2016se": "EstPropFemaleHouseholdNoSpouse_SE",
                        "estpropfemalehouseholdfamilychild_2016": "EstPropFemaleHouseholdFamilyChild",
                        "estpropfemalehouseholdfamilychild_2016se": "EstPropFemaleHouseholdFamilyChild_SE",
                        "estpropfemalehouseholdanychild_2016": "EstPropFemaleHouseholdAnyChild",
                        "estpropfemalehouseholdanychild_2016se": "EstPropFemaleHouseholdAnyChild_SE",
                        "estprophighschooldropout_2016": "EstPropHighSchoolDropout",
                        "estprophighschooldropoutnowork_2016": "EstPropHighSchoolDropoutNoWork",
                        "estprophouseholdssi_2016": "EstPropHouseholdSSI",
                        "estprophouseholdssi_2016se": "EstPropHouseholdSSI_SE",
                        "estprophouseholdpa_2016": "EstPropHouseholdPA",
                        "estprophouseholdpa_2016se": "EstPropHouseholdPA_SE",
                        "estpropmalelittlework_2016": "EstPropMaleLittleWork"}
    }
